spring:
  output:
    ansi:
      enabled: never
  lsp:
    name: wordcheck-sample-languageserver
    sample:
      wordcheck:
        words:
        - the
        - quick
        - brown
        - fox
        - jumps
        - over
        - lazy
        - dog
