logging:
  level:
    org.springframework.lsp.simplelanguageserver.SimpleLanguageServer: debug
spring:
  lsp:
    name: wordcheck-sample-languageserver
    sample:
      wordcheck:
        words:
        - the
        - quick
        - brown
        - fox
        - jumps
        - over
        - lazy
        - dog
